aaf:
    base:
        # Bootstrap - Allows unauthenticated access to administrative console
        bootstrap: false
        realms:
            api:
                active: true
            federated:
                active: true
                automate_login: true
                auto_provision: true
                development:
                    active: false
                sso_endpoint: "/Shibboleth.sso/Login"

                require:
                    sharedtoken: true
                    cn: true
                    email: true

                # Supported as fallback for problematic webservers
                # AAF webserver configuration shouldn't require this to be false.
                # See https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPAttributeAccess for more
                request:
                    attributes: true
                mapping:
                    principal: "persistent-id"   # The unique and persistent ID used to identify this principal for current and subsequent sessions (eduPersonTargetedID)
                    credential: "Shib-Session-ID"  # The internal session key assigned to the session associated with the request and hence the credential used
                    entityID: "Shib-Identity-Provider" # The entityID of the IdP that authenticated the subject associated with the request.

                    applicationID: "Shib-Application-ID" # The applicationId property derived for the request.
                    idpAuthenticationInstant: "Shib-Authentication-Instant"#// The ISO timestamp provided by the IdP indicating the time of authentication.

                    cn: "cn"
                    email: "mail"
                    sharedToken: "auEduPersonSharedToken"
        # Session Expiry Warning - minutes
        session_warning: 50
        session_decision_time: 5
        sms:
            api_endpoint: 'https://multitxt.vodafone.co.nz'
            api_key: 'reannz'
            api_secret: 'vlglh4rc'
            fake: false # Deliver via aaf.base.FakeSMSDeliveryController to GreenMail
    vhr:
        crypto:
            log_rounds: 6
            sha_rounds: 1024
        federationregistry:
            server: "https://registry.dev.tuakiri.ac.nz"
            api:
                organisations: "/federationregistry/api/v1/organizations/"
        login:
            ssl_only_cookie: true
            path: '/'
            validity_period_minutes: 2
            required_captcha_after_tries: 2
            consent_revocation_enabled: true
            consent_recovation_param_name: "_shib_idp_revokeConsent"
        passwordreset:
            second_factor_required: true
            reset_code_length: 6
            reset_sms_text: "Your VHR 'SMS Code' to reset your lost password is: {0}"
            reset_attempt_limit: 5
        scopes:
            base_scope: "vho.example.org"
        sharedtoken:
            sha_rounds: 1024
            idp_entityid: 'https://jgetty-test.reannz.co.nz/idp/shibboleth' # VHR Entity ID
        twosteplogin:
            issuer: "Tuakiri-DEV Virtual Home"

dataSource:
    jndiName: 'java:comp/env/jdbc/VHR'
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
        unique-names: true

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        grails:
            gsp:
                enable:
                    reload: true
            logging:
                jul:
                    usebridge: true
            resources:
                debug: true
        greenmail:
            disabled: false
    production:
        dataSource:
            dbCreate: 'update'
            dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        greenmail:
            disabled: true
        grails:
            resources:
                debug: false
            gsp:
                enable:
                    reload: false
            logging:
                jul:
                    usebridge: false
        testDataConfig:
            enabled: false
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        greenmail:
            disabled: true

grails:
    app:
        context: '/'
    application:
        name: 'Virtual Home'
    codegen:
        defaultPackage: virtualhome
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    mail:
        host: 'localhost'
        port: 'com.icegreen.greenmail.util.ServerSetupTest.SMTP.port'
        default:
            from: "tuakiri_dev_notifications@reannz.co.nz"
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        file:
            extensions: true
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
        use:
            accept:
                header: true
    profile: web
    serverURL: "https://jgetty-test.reannz.co.nz"
    urlmapping:
        cache:
            maxsize: 1000
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
            sitemesh:
                preprocess: true


hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

jasypt:
    algorithm: 'PBEWITHSHA256AND256BITAES-CBC-BC'
    providerName: 'BC'
    password: '<your very secret passphrase>'
    keyObtentionIterations: 1000

logging:
    level:
        root: INFO


recaptcha:
    publicKey: ""
    privateKey: ""
    includeNoScript: true
    forceLanguageInURL: false
    enable: true
    useSecureAPI: true


server:
    session:
        timeout: 3600
    servlet:
        context:
            # The order of the welcome pages is important.  JBoss deployment will break if index.gsp is first in the list.
            welcome-pages:
                - index.html
                - index.jsp
                - index.gsp

spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
